Traceback (most recent call last):
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\defaultprotocol.py", line 51, in call_callback
    self.callback(addr,data)
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\peerdiscovery\kademliadiscovery.py", line 191, in process_datagram
    msg += self.finders[unique_id].look_for
KeyError: b'c\xdaL(\xe0\xc4\xfd\xa4'
Traceback (most recent call last):
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\defaultprotocol.py", line 51, in call_callback
    self.callback(addr,data)
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\peerdiscovery\kademliadiscovery.py", line 191, in process_datagram
    msg += self.finders[unique_id].look_for
KeyError: b'c\xdaL(\xe0\xc4\xfd\xa4'
