Traceback (most recent call last):
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\defaultprotocol.py", line 51, in call_callback
    self.callback(addr,data)
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\peerdiscovery\kademliadiscovery.py", line 191, in process_datagram
    msg += self.finders[unique_id].look_for
KeyError: b'r\x00\xe2\xa8\xefh\xe4G'
Traceback (most recent call last):
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\defaultprotocol.py", line 51, in call_callback
    self.callback(addr,data)
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\peerdiscovery\kademliadiscovery.py", line 191, in process_datagram
    msg += self.finders[unique_id].look_for
KeyError: b'\x99\x8a\x14^\x0b\xce+\x08'
Traceback (most recent call last):
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\defaultprotocol.py", line 51, in call_callback
    self.callback(addr,data)
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\peerdiscovery\kademliadiscovery.py", line 191, in process_datagram
    msg += self.finders[unique_id].look_for
KeyError: b'\x87\xe8\xeb\x1d\xa9\nV\x16'
Traceback (most recent call last):
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\defaultprotocol.py", line 51, in call_callback
    self.callback(addr,data)
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\peerdiscovery\kademliadiscovery.py", line 191, in process_datagram
    msg += self.finders[unique_id].look_for
KeyError: b'r\x00\xe2\xa8\xefh\xe4G'
